-- ============================================
-- 간단한 DROP 스크립트 (테이블 먼저 삭제)
-- ============================================

-- 외래키 체크 비활성화
SET FOREIGN_KEY_CHECKS = 0;

-- 테이블 삭제 (자식부터)
DROP TABLE IF EXISTS `HEALTH_SURVEY_RESPONSE_ITEM`;
DROP TABLE IF EXISTS `HEALTH_SURVEY_QUESTION`;
DROP TABLE IF EXISTS `COMMENT`;
DROP TABLE IF EXISTS `MEMO`;
DROP TABLE IF EXISTS `KANBAN_CARD`;
DROP TABLE IF EXISTS `ARTIST_ASSIGNMENT`;
DROP TABLE IF EXISTS `KANBAN_BOARD`;
DROP TABLE IF EXISTS `PROJECT_MEMBER`;
DROP TABLE IF EXISTS `CALENDAR_EVENT`;
DROP TABLE IF EXISTS `MANAGER`;
DROP TABLE IF EXISTS `NOTIFICATION`;
DROP TABLE IF EXISTS `LEAVE_BALANCE`;
DROP TABLE IF EXISTS `ATTENDANCE_REQUEST`;
DROP TABLE IF EXISTS `ATTENDANCE`;
DROP TABLE IF EXISTS `DAILY_HEALTH_CHECK`;
DROP TABLE IF EXISTS `LEAVE_HISTORY`;
DROP TABLE IF EXISTS `NEW_REQUEST`;
DROP TABLE IF EXISTS `HEALTH_SURVEY`;
DROP TABLE IF EXISTS `PROJECT`;
DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `AGENCY`;
DROP TABLE IF EXISTS `health_survey_response`;
DROP TABLE IF EXISTS `task_history`;
DROP TABLE IF EXISTS `PROJECT_LEAVE_REQUEST`;

-- 외래키 체크 재활성화
SET FOREIGN_KEY_CHECKS = 1;