-- MANAGER 테이블 및 ARTIST_ASSIGNMENT 테이블 생성
-- ERD 구조에 맞게 수정된 마이그레이션 스크립트

-- 1. MANAGER 테이블 생성
CREATE TABLE IF NOT EXISTS `MANAGER` (
    `MANAGER_NO` BIGINT NOT NULL AUTO_INCREMENT,
    `MEMBER_NO` BIGINT NOT NULL COMMENT '멤버 번호 (MEMBER 테이블 참조)',
    PRIMARY KEY (`MANAGER_NO`),
    CONSTRAINT `FK_MANAGER_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `UK_MANAGER_MEMBER_NO` (`MEMBER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='담당자 테이블';

-- 2. ARTIST_ASSIGNMENT 테이블 생성
CREATE TABLE IF NOT EXISTS `ARTIST_ASSIGNMENT` (
    `ARTIST_ASSIGNMENT_NO` BIGINT NOT NULL AUTO_INCREMENT,
    `ARTIST_MEMBER_NO` BIGINT NOT NULL COMMENT '작가 멤버 번호 (MEMBER 테이블 참조)',
    `MANAGER_NO` BIGINT NOT NULL COMMENT '담당자 번호 (MANAGER 테이블 참조)',
    PRIMARY KEY (`ARTIST_ASSIGNMENT_NO`),
    CONSTRAINT `FK_ARTIST_ASSIGNMENT_MEMBER` FOREIGN KEY (`ARTIST_MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_ARTIST_ASSIGNMENT_MANAGER` FOREIGN KEY (`MANAGER_NO`) REFERENCES `MANAGER`(`MANAGER_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `UK_ARTIST_MANAGER` (`ARTIST_MEMBER_NO`, `MANAGER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작가-담당자 배정 테이블';

-- 3. 기존 '담당자' 역할의 멤버들을 MANAGER 테이블에 등록
INSERT INTO `MANAGER` (`MEMBER_NO`)
SELECT `MEMBER_NO` 
FROM `MEMBER` 
WHERE `MEMBER_ROLE` = '담당자'
ON DUPLICATE KEY UPDATE `MEMBER_NO` = `MEMBER_NO`;

-- 4. 인덱스 추가 (조회 성능 향상)
CREATE INDEX `IDX_MANAGER_MEMBER_NO` ON `MANAGER` (`MEMBER_NO`);
CREATE INDEX `IDX_ARTIST_ASSIGNMENT_ARTIST` ON `ARTIST_ASSIGNMENT` (`ARTIST_MEMBER_NO`);
CREATE INDEX `IDX_ARTIST_ASSIGNMENT_MANAGER` ON `ARTIST_ASSIGNMENT` (`MANAGER_NO`);
