-- PORTFOLIO 테이블 추가 및 PROJECT_MEMBER 컬럼 추가 (기존 DB 적용용)
-- 출처: PORTFOLIO_테이블_및_PROJECT_MEMBER_수정_내역.md (옵션 2: ALTER TABLE로 추가)
-- 실행 전 백업 권장. 새 DB는 schema.sql 전체 실행 시 포함됨.

-- 1) PORTFOLIO 테이블 생성 (제약조건 제외)
CREATE TABLE IF NOT EXISTS `PORTFOLIO` (
	`PORTFOLIO_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NULL,
	`PORTFOLIO_USER_NAME`	VARCHAR(50)	NULL,
	`PORTFOLIO_USER_PHONE`	VARCHAR(20)	NULL,
	`PORTFOLIO_USER_EMAIL`	VARCHAR(100)	NULL,
	`PORTFOLIO_USER_CAREER`	VARCHAR(2000)	NULL,
	`PORTFOLIO_USER_PROJECT`	VARCHAR(2000)	NULL,
	`PORTFOLIO_USER_SKILL`	VARCHAR(2000)	NULL,
	`PORTFOLIO_STATUS`	VARCHAR(2)	NOT NULL	DEFAULT 'Y'	COMMENT 'Y/N(활성/삭제)',
	`PORTFOLIO_CREATED_AT`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`PORTFOLIO_UPDATED_AT`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2) 기본키 제약조건 추가
ALTER TABLE `PORTFOLIO` ADD CONSTRAINT `PK_PORTFOLIO` PRIMARY KEY (`PORTFOLIO_NO`);

-- 3) AUTO_INCREMENT 적용
ALTER TABLE `PORTFOLIO` MODIFY `PORTFOLIO_NO` BIGINT NOT NULL AUTO_INCREMENT;

-- 4) 외래키 제약조건 추가 (ON DELETE SET NULL)
ALTER TABLE `PORTFOLIO` ADD CONSTRAINT `FK_PORTFOLIO_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`) ON DELETE SET NULL;

-- 5) PROJECT_MEMBER 테이블 컬럼 추가
ALTER TABLE `PROJECT_MEMBER` ADD COLUMN `PROJECT_MEMBER_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `PROJECT_MEMBER` ADD COLUMN `PROJECT_MEMBER_ENDED_AT` DATETIME NULL;

-- 6) 기존 데이터의 PROJECT_MEMBER_CREATED_AT 초기화 (선택사항)
-- UPDATE `PROJECT_MEMBER` SET `PROJECT_MEMBER_CREATED_AT` = CURRENT_TIMESTAMP WHERE `PROJECT_MEMBER_CREATED_AT` IS NULL;
