-- 담당자-작가 배정 관계를 위한 MANAGER_NO 컬럼 추가
-- 실행 전 백업 권장

-- 1. MANAGER_NO 컬럼 추가
ALTER TABLE `MEMBER` 
ADD COLUMN `MANAGER_NO` BIGINT NULL COMMENT '담당자 번호 (작가가 담당자를 가리키는 외래키)' AFTER `MEMBER_ROLE`;

-- 2. 외래키 제약조건 추가 (선택사항 - 데이터 무결성을 위해 권장)
ALTER TABLE `MEMBER`
ADD CONSTRAINT `FK_MEMBER_MANAGER` 
FOREIGN KEY (`MANAGER_NO`) 
REFERENCES `MEMBER` (`MEMBER_NO`) 
ON DELETE SET NULL 
ON UPDATE CASCADE;

-- 3. 인덱스 추가 (조회 성능 향상)
CREATE INDEX `IDX_MEMBER_MANAGER_NO` ON `MEMBER` (`MANAGER_NO`);
