-- PORTFOLIO 테이블에 Notion 연동 컬럼 추가 (이미 있으면 실행 제외)
ALTER TABLE `PORTFOLIO` ADD COLUMN `NOTION_PAGE_ID` VARCHAR(36) NULL COMMENT 'Notion 페이지 ID';
ALTER TABLE `PORTFOLIO` ADD COLUMN `NOTION_PAGE_URL` VARCHAR(500) NULL COMMENT 'Notion 페이지 URL';
