    -- ============================================
-- 팀원용 스키마 생성 스크립트
-- ============================================

-- ============================================
-- 1단계: 테이블 생성
-- ============================================
CREATE TABLE IF NOT EXISTS `AGENCY` (
	`AGENCY_NO`	BIGINT	NOT NULL,
	`AGENCY_NAME`	VARCHAR(30)	NULL,
	`AGENCY_CODE`	VARCHAR(11)	NULL,
	`AGENCY_LEAVE`  INT DEFAULT '15'
);

CREATE TABLE IF NOT EXISTS `MEMBER` (
	`MEMBER_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NULL,
	`MEMBER_NAME`	VARCHAR(20)	NOT NULL,
	`MEMBER_ID`	VARCHAR(20)	NOT NULL	COMMENT 'UNIQUE',
	`MEMBER_PASSWORD`	VARCHAR(100)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR(50)	NOT NULL,
	`MEMBER_PHONE`	VARCHAR(15)	NOT NULL,
	`MEMBER_ADDRESS`    VARCHAR(100),
	`MEMBER_STATUS`	VARCHAR(20)	NOT NULL	COMMENT '활성 / 휴면 (ACTIVE /  BLOCKED)',
	`MEMBER_PROFILE_IMAGE`	VARCHAR(100)	NULL,
	`MEMBER_PROFILE_BANNER_IMAGE`	VARCHAR(100)	NULL,
	`MEMBER_ROLE`	VARCHAR(100)	NOT NULL	COMMENT '웹툰 작가 / 웹소설 작가 / 어시스트 - 채색 / 어시스트 - 조명 / 어시스트 - 배경 / 어시스트 - 선화 / 어시스트- 기타 / 에이전시 관리자 / 담당자',
	`MEMBER_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`MEMBER_UPDATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `PROJECT` (
	`PROJECT_NO`	BIGINT	NOT NULL,
	`PROJECT_NAME`	VARCHAR(100)	NOT NULL,
	`PROJECT_STATUS`	VARCHAR(100)	NOT NULL	DEFAULT '연재'	COMMENT '연재 / 휴재 / 완결',
	`PROJECT_COLOR`	VARCHAR(50)	NOT NULL	DEFAULT '기본색',
	`PROJECT_CYCLE` INT	NULL,
	`THUMBNAIL_FILE` VARCHAR(500)	NULL,
	`PROJECT_STARTED_AT` DATETIME	NULL
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY` (
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_NAME`	VARCHAR(100)	NULL,
	`HEALTH_SURVEY_TYPE`	VARCHAR(30)	NULL	COMMENT '데일리/월간신체/월간정신',
	`HEALTH_SURVEY_CONTENT`	VARCHAR(30)	NULL,
	`HEALTH_SURVEY_STATUS`	VARCHAR(1)	NOT NULL	COMMENT '미검진 / 검진완료 ( Y / N )',
	`HEALTH_SURVEY_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`HEALTH_SURVEY_UPDATED_AT`	DATETIME	NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `CALENDAR_EVENT` (
	`CALENDAR_EVENT_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`CALENDAR_EVENT_NAME`	VARCHAR(50)	NULL,
	`CALENDAR_EVENT_CONTENT`	VARCHAR(100)	NULL,
	`CALENDAR_EVENT_TYPE`	VARCHAR(20)	NULL,
	`CALENDAR_EVENT_STARTED_AT`	DATE	NOT NULL,
	`CALENDAR_EVENT_ENDED_AT`	DATE	NOT NULL,
	`CALENDAR_EVENT_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`CALENDAR_EVENT_UPDATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CALENDAR_EVENT_COLOR`	VARCHAR(10)	NULL
);

CREATE TABLE IF NOT EXISTS `NOTIFICATION` (
	`NOTIFICATION_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`NOTIFICATION_NAME`	VARCHAR(30)	NULL,
	`NOTIFICATION_TEXT`	VARCHAR(260)	NULL,
	`NOTIFICATION_CREATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP,
	`NOTIFICATION_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT 'Y / N',
	`NOTIFICATION_TYPE`	VARCHAR(10)	NULL
);

CREATE TABLE IF NOT EXISTS `LEAVE_BALANCE` (
	`LEAVE_BALANCE_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`LEAVE_TYPE`	VARCHAR(20)	NOT NULL	DEFAULT 'ANNUAL'	COMMENT '연차 / 대체휴무 / 특별휴가',
	`LEAVE_BALANCE_TOTAL_DAYS`	INT	NOT NULL,
	`LEAVE_BALANCE_USED_DAYS`	INT DEFAULT '0'	NULL,
	`LEAVE_BALANCE_REMAIN_DAYS`	INT	NULL,
	`LEAVE_BALANCE_YEAR`	VARCHAR(4)	NOT NULL,
	`LEAVE_BALANCE_UPDATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ATTENDANCE_REQUEST` (
	`ATTENDANCE_REQUEST_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`ATTENDANCE_REQUEST_TYPE`	VARCHAR(20)	NOT NULL	COMMENT '연차 / 병가 / 워케이션 / 재택 / 휴재',
	`ATTENDANCE_REQUEST_START_DATE`	DATE	NOT NULL,
	`ATTENDANCE_REQUEST_END_DATE`	DATE	NOT NULL,
	`ATTENDANCE_REQUEST_USING_DAYS`	INT	NOT NULL,
	`ATTENDANCE_REQUEST_REASON`	VARCHAR(255)	NULL,
	`WORKCATION_LOCATION`	VARCHAR(100)	NULL	COMMENT '워케이션 신청 시에만 작성',
	`MEDICAL_FILE_URL`	VARCHAR(500)	NOT NULL,
	`ATTENDANCE_REQUEST_STATUS`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '신청 / 승인 / 반려 / 취소',
	`ATTENDANCE_REQUEST_REJECT_REASON`	VARCHAR(200)	NULL,
	`ATTENDANCE_REQUEST_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`ATTENDANCE_REQUEST_UPDATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ATTENDANCE` (
	`ATTENDANCE_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`ATTENDANCE_TYPE`	VARCHAR(10)	NOT NULL	COMMENT '출근, 퇴근',
	`ATTENDANCE_TIME`	DATETIME	NOT NULL
);

CREATE TABLE IF NOT EXISTS `PROJECT_MEMBER` (
	`PROJECT_MEMBER_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`PROJECT_NO`	BIGINT	NOT NULL,
	`PROJECT_MEMBER_ROLE`	VARCHAR(50)	NOT NULL	DEFAULT 'MEMBER'	COMMENT 'LEADER / MEMBER'
);

CREATE TABLE IF NOT EXISTS `KANBAN_BOARD` (
	`KANBAN_BOARD_NO`	BIGINT	NOT NULL,
	`PROJECT_NO`	BIGINT	NOT NULL,
	`KANBAN_BOARD_NAME`	VARCHAR(100)	NULL,
	`KANBAN_BOARD_ORDER`	INT	NOT NULL,
	`KANBAN_BOARD_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT 'Y / N'
);

CREATE TABLE IF NOT EXISTS `KANBAN_CARD` (
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`BOARD_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NAME`	VARCHAR(50)	NOT NULL,
	`KANBAN_CARD_STATUS`	VARCHAR(1)  DEFAULT 'N'	NOT NULL	COMMENT '완료 / 미완료 ( Y / N )',
	`KANBAN_CARD_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`KANBAN_CARD_UPDATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`PROJECT_MEMBER_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_STARTED_AT`	DATE	NULL,
	`KANBAN_CARD_ENDED_AT`	DATE	NULL
);

CREATE TABLE IF NOT EXISTS `COMMENT` (
	`COMMENT_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`COMMENT_CONTENT`	VARCHAR(1000)	NULL
);

CREATE TABLE IF NOT EXISTS `TASK_HISTORY` (
	`TASK_HISTORY_NO`	BIGINT	NOT NULL,
	`KANBAN_CARD_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`BEFORE_TASK_HISTORY`	VARCHAR(1000)	NULL,
	`AFTER_TASK_HISTORY`	VARCHAR(1000)	NULL,
	`TASK_HISTORY_UPDATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `MEMO` (
	`MEMO_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`CALENDAR_EVENT_NO`	BIGINT	NOT NULL,
	`MEMO_NAME`	VARCHAR(30)	NOT NULL,
	`MEMO_TEXT`	VARCHAR(255)	NULL,
	`MEMO_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`MEMO_UPDATED_AT`	DATETIME	NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`MEMO_TYPE`	VARCHAR(12)	NULL	COMMENT '개인메모/캘린더메모'
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY_QUESTION` (
	`HEALTH_SURVEY_QUESTION_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_ORDER`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_CONTENT`	VARCHAR(1000)	NULL,
	`HEALTH_SURVEY_QUESTION_MIN_SCORE`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_MAX_SCORE`	INT	NULL,
	`HEALTH_SURVEY_QUESTION_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
	`HEALTH_SURVEY_QUESTION_UPDATED_AT`	DATETIME	NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY_RESPONSE` (
	`HEALTH_SURVEY_RESPONSE_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_RESPONSE_TOTAL_SCORE`	INT	NULL,
	`HEALTH_SURVEY_RESPONSE_STATUS`	VARCHAR(1)	NOT NULL	COMMENT '완료 / 미완료 (Y / N)',
	`HEALTH_SURVEY_RESPONSE_CREATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `HEALTH_SURVEY_RESPONSE_ITEM` (
	`HEALTH_SURVEY_RESPONSE_ITEM_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_RESPONSE_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_QUESTION_NO`	BIGINT	NOT NULL,
	`HEALTH_SURVEY_QUESTION_ITEM_ANSWER_SCORE`	INT	NOT NULL	COMMENT '0 / 1 / 2 / 3',
	`HEALTH_SURVEY_QUESTION_ITEM_CREATED_AT`	DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `DAILY_HEALTH_CHECK` (
	`HEALTH_CHECK_NO`	BIGINT	NOT NULL,
    `MEMBER_NO`	BIGINT	NOT NULL,
    `HEALTH_CONDITION`	VARCHAR(20)	NULL,
    `SLEEP_HOURS`	INT	NULL,
    `DISCOMFORT_LEVEL`	INT	NULL,
    `HEALTH_CHECK_NOTES`	VARCHAR(1000)	NULL,
    `HEALTH_CHECK_CREATED_AT`	DATETIME    NULL    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `LEAVE_HISTORY` (
	`LEAVE_HISTORY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`LEAVE_HISTORY_DATE`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP,
	`LEAVE_HISTORY_TYPE`	VARCHAR(30)	NOT NULL	COMMENT '경력인정/징계/포상',
	`LEAVE_HISTORY_REASON`	VARCHAR(1000)	NULL,
	`LEAVE_HISTORY_AMOUNT`	INT	NOT NULL
);

CREATE TABLE IF NOT EXISTS `NEW_REQUEST` (
	`NEW_REQUEST_NO`	BIGINT	NOT NULL,
	`AGENCY_NO`	BIGINT	NOT NULL,
	`MEMBER_NO`	BIGINT	NOT NULL,
	`NEW_REQUEST_DATE`	DATETIME	NULL,
	`NEW_REQUEST_STATUS`	VARCHAR(10)	NULL	COMMENT '승인/대기/거절'
);

CREATE TABLE IF NOT EXISTS `MANAGER` (
    `MANAGER_NO`  BIGINT  NOT NULL COMMENT '담당자 번호',
    `MEMBER_NO`   BIGINT  NOT NULL COMMENT '회원 번호'
);

CREATE TABLE IF NOT EXISTS `ARTIST_ASSIGNMENT` (
    `ARTIST_ASSIGNMENT_NO` BIGINT NOT NULL COMMENT '작가 배정 번호',
    `ARTIST_MEMBER_NO`     BIGINT NOT NULL COMMENT '작가 회원 번호',
    `MANAGER_NO`           BIGINT NOT NULL COMMENT '담당자 번호'
);

-- ============================================
-- 2단계: 기본키 제약조건 추가
-- ============================================
ALTER TABLE `AGENCY` ADD CONSTRAINT `PK_AGENCY` PRIMARY KEY (`AGENCY_NO`);
ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (`MEMBER_NO`);
ALTER TABLE `PROJECT` ADD CONSTRAINT `PK_PROJECT` PRIMARY KEY (`PROJECT_NO`);
ALTER TABLE `HEALTH_SURVEY` ADD CONSTRAINT `PK_HEALTH_SURVEY` PRIMARY KEY (`HEALTH_SURVEY_NO`);
ALTER TABLE `CALENDAR_EVENT` ADD CONSTRAINT `PK_CALENDAR_EVENT` PRIMARY KEY (`CALENDAR_EVENT_NO`);
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `PK_NOTIFICATION` PRIMARY KEY (`NOTIFICATION_NO`);
ALTER TABLE `LEAVE_BALANCE` ADD CONSTRAINT `PK_LEAVE_BALANCE` PRIMARY KEY (`LEAVE_BALANCE_NO`);
ALTER TABLE `ATTENDANCE_REQUEST` ADD CONSTRAINT `PK_ATTENDANCE_REQUEST` PRIMARY KEY (`ATTENDANCE_REQUEST_NO`);
ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (`ATTENDANCE_NO`);
ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `PK_PROJECT_MEMBER` PRIMARY KEY (`PROJECT_MEMBER_NO`);
ALTER TABLE `KANBAN_BOARD` ADD CONSTRAINT `PK_KANBAN_BOARD` PRIMARY KEY (`KANBAN_BOARD_NO`);
ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `PK_KANBAN_CARD` PRIMARY KEY (`KANBAN_CARD_NO`);
ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (`COMMENT_NO`);
ALTER TABLE `TASK_HISTORY` ADD CONSTRAINT `PK_TASK_HISTORY` PRIMARY KEY (`TASK_HISTORY_NO`);
ALTER TABLE `MEMO` ADD CONSTRAINT `PK_MEMO` PRIMARY KEY (`MEMO_NO`);
ALTER TABLE `HEALTH_SURVEY_QUESTION` ADD CONSTRAINT `PK_HEALTH_SURVEY_QUESTION` PRIMARY KEY (`HEALTH_SURVEY_QUESTION_NO`);
ALTER TABLE `HEALTH_SURVEY_RESPONSE` ADD CONSTRAINT `PK_HEALTH_SURVEY_RESPONSE` PRIMARY KEY (`HEALTH_SURVEY_RESPONSE_NO`);
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `PK_HEALTH_SURVEY_RESPONSE_ITEM` PRIMARY KEY (`HEALTH_SURVEY_RESPONSE_ITEM_NO`);
ALTER TABLE `DAILY_HEALTH_CHECK` ADD CONSTRAINT `PK_DAILY_HEALTH_CHECK` PRIMARY KEY (`HEALTH_CHECK_NO`);
ALTER TABLE `MANAGER` ADD CONSTRAINT `PK_MANAGER` PRIMARY KEY (`MANAGER_NO`);
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `PK_ARTIST_ASSIGNMENT` PRIMARY KEY (`ARTIST_ASSIGNMENT_NO`);

-- ============================================
-- 3단계: AUTO_INCREMENT 적용 (외래키 추가 전에!)
-- ============================================
ALTER TABLE `AGENCY` MODIFY `AGENCY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `MEMBER` MODIFY `MEMBER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PROJECT` MODIFY `PROJECT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY` MODIFY `HEALTH_SURVEY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `CALENDAR_EVENT` MODIFY `CALENDAR_EVENT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `NOTIFICATION` MODIFY `NOTIFICATION_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `LEAVE_BALANCE` MODIFY `LEAVE_BALANCE_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `ATTENDANCE_REQUEST` MODIFY `ATTENDANCE_REQUEST_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `ATTENDANCE` MODIFY `ATTENDANCE_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PROJECT_MEMBER` MODIFY `PROJECT_MEMBER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `KANBAN_BOARD` MODIFY `KANBAN_BOARD_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `KANBAN_CARD` MODIFY `KANBAN_CARD_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `COMMENT` MODIFY `COMMENT_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `TASK_HISTORY` MODIFY `TASK_HISTORY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `MEMO` MODIFY `MEMO_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY_QUESTION` MODIFY `HEALTH_SURVEY_QUESTION_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY_RESPONSE` MODIFY `HEALTH_SURVEY_RESPONSE_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` MODIFY `HEALTH_SURVEY_RESPONSE_ITEM_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `DAILY_HEALTH_CHECK` MODIFY `HEALTH_CHECK_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `LEAVE_HISTORY` MODIFY `LEAVE_HISTORY_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `NEW_REQUEST` MODIFY `NEW_REQUEST_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `MANAGER` MODIFY `MANAGER_NO` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `ARTIST_ASSIGNMENT` MODIFY `ARTIST_ASSIGNMENT_NO` BIGINT NOT NULL AUTO_INCREMENT;

-- ============================================
-- 4단계: UNIQUE 제약조건 추가
-- ============================================
-- AGENCY 관련
ALTER TABLE `AGENCY` ADD CONSTRAINT `UK_AGENCY_NAME` UNIQUE (`AGENCY_NAME`);
ALTER TABLE `AGENCY` ADD CONSTRAINT `UK_AGENCY_CODE` UNIQUE (`AGENCY_CODE`);

-- MEMBER 관련
ALTER TABLE `MEMBER` ADD CONSTRAINT `UK_MEMBER_ID` UNIQUE (`MEMBER_ID`);

-- MANAGER 관련
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `UK_MANAGER_ARTIST` UNIQUE (`MANAGER_NO`, `ARTIST_MEMBER_NO`);

-- ============================================
-- 5단계: 외래키 제약조건 추가 (AUTO_INCREMENT 적용 후)
-- ============================================
-- AGENCY 관련

ALTER TABLE `MEMBER` ADD CONSTRAINT `FK_MEMBER_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);
ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_ATTENDANCE_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);
ALTER TABLE `NEW_REQUEST` ADD CONSTRAINT `FK_NEW_REQUEST_AGENCY` FOREIGN KEY (`AGENCY_NO`) REFERENCES `AGENCY`(`AGENCY_NO`);

-- MEMBER 관련
ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `FK_PROJECT_MEMBER_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `FK_NOTIFICATION_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `LEAVE_BALANCE` ADD CONSTRAINT `FK_LEAVE_BALANCE_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `ATTENDANCE_REQUEST` ADD CONSTRAINT `FK_ATTENDANCE_REQUEST_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `CALENDAR_EVENT` ADD CONSTRAINT `FK_CALENDAR_EVENT_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `MEMO` ADD CONSTRAINT `FK_MEMO_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `TASK_HISTORY` ADD CONSTRAINT `FK_TASK_HISTORY_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `HEALTH_SURVEY_RESPONSE` ADD CONSTRAINT `FK_HEALTH_SURVEY_RESPONSE_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_ATTENDANCE_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `DAILY_HEALTH_CHECK` ADD CONSTRAINT `FK_DAILY_HEALTH_CHECK_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `LEAVE_HISTORY` ADD CONSTRAINT `FK_LEAVE_HISTORY_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `NEW_REQUEST` ADD CONSTRAINT `FK_NEW_REQUEST_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER`(`MEMBER_NO`);
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `FK_ARTIST_ASSIGNMENT_ARTIST` FOREIGN KEY (`ARTIST_MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);
ALTER TABLE `MANAGER` ADD CONSTRAINT `FK_MANAGER_MEMBER` FOREIGN KEY (`MEMBER_NO`) REFERENCES `MEMBER` (`MEMBER_NO`);

-- PROJECT 관련
ALTER TABLE `KANBAN_BOARD` ADD CONSTRAINT `FK_KANBAN_BOARD_PROJECT` FOREIGN KEY (`PROJECT_NO`) REFERENCES `PROJECT`(`PROJECT_NO`);
ALTER TABLE `PROJECT_MEMBER` ADD CONSTRAINT `FK_PROJECT_MEMBER_PROJECT` FOREIGN KEY (`PROJECT_NO`) REFERENCES `PROJECT`(`PROJECT_NO`);

-- KANBAN_BOARD 관련
ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `FK_KANBAN_CARD_BOARD` FOREIGN KEY (`BOARD_NO`) REFERENCES `KANBAN_BOARD`(`KANBAN_BOARD_NO`);

-- PROJECT_MEMBER 관련
ALTER TABLE `KANBAN_CARD` ADD CONSTRAINT `FK_KANBAN_CARD_PROJECT_MEMBER` FOREIGN KEY (`PROJECT_MEMBER_NO`) REFERENCES `PROJECT_MEMBER`(`PROJECT_MEMBER_NO`);

-- KANBAN_CARD 관련
ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_COMMENT_CARD` FOREIGN KEY (`KANBAN_CARD_NO`) REFERENCES `KANBAN_CARD`(`KANBAN_CARD_NO`);
ALTER TABLE `TASK_HISTORY` ADD CONSTRAINT `FK_TASK_HISTORY_CARD` FOREIGN KEY (`KANBAN_CARD_NO`) REFERENCES `KANBAN_CARD`(`KANBAN_CARD_NO`);

-- CALENDAR_EVENT 관련
ALTER TABLE `MEMO` ADD CONSTRAINT `FK_MEMO_CALENDAR_EVENT` FOREIGN KEY (`CALENDAR_EVENT_NO`) REFERENCES `CALENDAR_EVENT`(`CALENDAR_EVENT_NO`);

-- HEALTH_SURVEY 관련
ALTER TABLE `HEALTH_SURVEY_QUESTION` ADD CONSTRAINT `FK_HEALTH_SURVEY_QUESTION_SURVEY` FOREIGN KEY (`HEALTH_SURVEY_NO`) REFERENCES `HEALTH_SURVEY`(`HEALTH_SURVEY_NO`);
ALTER TABLE `HEALTH_SURVEY_RESPONSE` ADD CONSTRAINT `FK_HEALTH_SURVEY_RESPONSE_SURVEY` FOREIGN KEY (`HEALTH_SURVEY_NO`) REFERENCES `HEALTH_SURVEY`(`HEALTH_SURVEY_NO`);

-- HEALTH_SURVEY_QUESTION 관련
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `FK_HEALTH_SURVEY_RESPONSE_ITEM_QUESTION` FOREIGN KEY (`HEALTH_SURVEY_QUESTION_NO`) REFERENCES `HEALTH_SURVEY_QUESTION`(`HEALTH_SURVEY_QUESTION_NO`);

-- HEALTH_SURVEY_RESPONSE 관련
ALTER TABLE `HEALTH_SURVEY_RESPONSE_ITEM` ADD CONSTRAINT `FK_HEALTH_SURVEY_RESPONSE_ITEM_RESPONSE` FOREIGN KEY (`HEALTH_SURVEY_RESPONSE_NO`) REFERENCES `HEALTH_SURVEY_RESPONSE`(`HEALTH_SURVEY_RESPONSE_NO`);

-- MANAGER 관련
ALTER TABLE `ARTIST_ASSIGNMENT` ADD CONSTRAINT `FK_ARTIST_ASSIGNMENT_MANAGER` FOREIGN KEY (`MANAGER_NO`) REFERENCES `MANAGER` (`MANAGER_NO`);
